### ISSUE TITLE
Home Assistant temperature entities use incorrect units

### ISSUE THREAD

**Issue by ascendedguard** [Luligu/matterbridge#374]
**Describe the bug**
Unsure if this a matterbridge issue, or a hass plugin issue, so putting it here.

Temperatures from Home Assistant show in Google Home incorrectly as Celsius, but appear to be interpreted as Fahrenheit (or unit-less?) regardless. This leads to things like thermostats showing an extremely low temperature on gauges.

The odd thing is that the temperature shows correct (73 in my case) when I first restart Matterbridge and refresh in the Google Home app. It's only after Matterbridge is fully loaded and all devices populate in Google Home that suddenly it reverts to a low number ex. 23.

This seems consistent across all devices - Ecobee is via Homekit, and various sensors are via zwave.

**To Reproduce**
1. Install hass plugin and import entities. HA is configured for Fahrenheit
2. Scan QR code with Google Home and import devices

**Expected behavior**
Configured units should be respected

**Screenshots**
<img width="1440" height="3120" alt="Image" src="https://github.com/user-attachments/assets/fe823c1d-6e6d-424c-bd3c-f1bc8b8f49e7" />

**Debug file**
[matterbridge.log](https://github.com/user-attachments/files/21708418/matterbridge.log)
[matter.log](https://github.com/user-attachments/files/21708419/matter.log)

**Plugin (please complete the following information):**

- matterbridge-hass v0.2.1 (note - it's been the same since I originally installed about a week ago)

**Matterbridge (please complete the following information):**

- Mode: Docker
- Version: 3.2.2
- OS: via Docker on Ubuntu 24.04

**Comment by Luligu** [comment]
Hi,
the Matter cluster is in Celsius.

Then the controller shows how the user selects.

How is your unit settings in Hass ?

The matterbridge log is empty...

Show me a screenshot of the device in Hass please and a screenshot of IconView in matterbridge frontend.

**Comment by ascendedguard** [comment]
![Screenshot_20250813-001033.png](https://github.com/user-attachments/assets/55c893b3-cf68-4386-8ef9-79864b3ee055)

![Screenshot_20250813-001145.png](https://github.com/user-attachments/assets/8e41aa9e-18d1-46ac-93fd-15643278a77d)

I'm not sure if this is what you meant by IconView, let me know if you need something else.

![Screenshot_20250813-001311.png](https://github.com/user-attachments/assets/0a62281a-41ba-4ffe-a0c6-c1d607a69539)

Here's the Den sensor in HA since that also shows in the previous screenshot

![Screenshot_20250813-001409.png](https://github.com/user-attachments/assets/6ddc9836-3263-45fc-81ba-4b76f21fce0f)

**Comment by Luligu** [comment]
Ok all seems good to me.
Your HA is in F and shows in F.
The Matterbridge frontend shows correctly in C (as told is the correct unit in Matter) cause the plugin correctly converted them.

If you have issues on the UI of controller check there cause here all is correct.

I will fix the overflow...

**Comment by ascendedguard** [comment]
I'm continuing to investigate some on my end when I have time.

From the Google Home side:
* Changing the weather units from F to C, and then back to F does not fix anything. I tried this in both the Google Assistant weather settings, and the Pixel Weather settings (both of which were suggested as "fixes" for Google Home unit issues).
* I can confirm when Home Assistant was connected to Google via the google_assistant integration, these devices _did_ show correctly.

Here's an updated matterbridge log - I didn't realize the matter log level was separate from matterbridge log level.
[matterbridge(1).log](https://github.com/user-attachments/files/21945570/matterbridge.1.log)

So far, I suspect it might just be an issue with Google's implementation of Matter. I confirmed the "Den" and "My Ecobee" units are actually in Celsius by adding them to favorites, which does display the units, and cannot find any way to change Google Home to display Fahrenheit instead.

**Comment by ascendedguard** [comment]
Not necessarily useful, but it seems other devices might have the same issue: https://forum.aqara.com/t/google-home-fahrenheit/8107/2

There's also multiple threads talking about Google getting units wrong: [here](https://www.reddit.com/r/googlehome/comments/1h9jjn2/defaulting_to_fahrenheit_repeatedly/) and [here](https://support.google.com/assistant/thread/313264230?hl=en&msgid=313467659) although they're more generally Google Home and not specifically Matter.

I was considering disconnecting Matterhome from Google and reconnecting them, but I'm not sure how to do that on either side outside of disconnecting each device one by one.

**Comment by Luligu** [comment]
Hi,
for the log: matterbridge.log already includes matter.log.
Matter.log is also single to help debug specific matter issues.

For Google Home I cannot help you cause I don't have it.

Maybe join the Discord group and ask Tamer about it or other users in North America.

**Comment by bobloadmire** [comment]
Was there any fox for this?

**Comment by Luligu** [comment]
> Was there any fox for this?

All is fixed

**Comment by AltyFox** [comment]
> > Was there any fox for this?
> 
> All is fixed

How did you fix it?  I'm stilll havving issues.

**Comment by ascendedguard** [comment]
> > > Was there any fox for this?
> > 
> > All is fixed
> 
> How did you fix it?  I'm stilll havving issues.

It's still broken for me too, I never found a fix. I've kind of assumed it's a Google issue but I'm not really sure, I found one page where it listed that the temperature was C, but every other page and display and gauge treats it as F (without showing units) causing it to be completely unusable.

I didn't ask in the Discord, I kind of gave up before that.

**Comment by Luligu** [comment]
Hi,
kindly check that on matterbridge frontend (Devices page) you see the correct temperature. there must be C and not F.
As I wrote, Matter shows temperatures in C. 
The controller then should remap to F when is the case.
